UI_regression_discontinuity <- tabPanel(title = "Regression discontinuity",
         sidebarLayout(
           sidebarPanel(
             width = 5,
             includeMarkdown('markdowns/regression_discontinuity.md'),
             br(),
             tabsetPanel(
               id = 'disc_tabs_left',
               type = 'tabs',
               tabPanel(
                 "Analysis tools",
                 br(),
                 selectInput(inputId = "disc_select_model",
                             label = "Modeled relationship:",
                             choices = c("Linear", "Polynomial - quadratic", "Polynomial - cubic", 'Difference in means'),
                             selected = "Linear",
                             multiple = FALSE),
                 sliderInput(inputId = 'disc_numeric_window',
                             label = 'Bandwidth:',
                             min = 1,
                             max = 80,
                             value = 10,
                             step = 1,
                             animate = animationOptions(interval = 400, loop = FALSE)),
                 br(),
                 h4("Estimate of tau at the cutoff by model type:"),
                 htmlOutput('disc_table')
               ),
               tabPanel(
                 'Data generation process',
                 br(),
                 selectInput(inputId = "disc_select_DGP",
                             label = "True relationship:",
                             choices = c("Linear", "Polynomial - quadratic", "Polynomial - cubic"),
                             selected = "Linear",
                             multiple = FALSE),
                 helpText('These examples assume the same functional form across the two groups but that is not explicitly neccessary in practice.'),
                 br(),
                 sliderInput(inputId = "disc_numeric_tau",
                             label = "True difference (tau) at the cutoff:",
                             min = 0, 
                             max = 20, 
                             step = 1,
                             value = 5),
                 sliderInput(inputId = "disc_numeric_cutoff",
                             label = "Cutoff age:",
                             min = 30, 
                             max = 70, 
                             step = 1,
                             value = 50),
                 sliderInput(
                   inputId = "disc_slider_error",
                   label = "Error:",
                   value = 5,
                   min = 0,
                   max = 10,
                   step = 1),
                 sliderInput(inputId = "disc_numeric_n",
                             label = "n:",
                             min = 100, 
                             max = 1000, 
                             step = 50,
                             value = 250),
                 conditionalPanel(
                   condition = "input.disc_select_DGP == 'Linear'",
                   sliderInput(inputId = "disc_slider_slope",
                               label = "Slope:",
                               min = 0,
                               max = 1,
                               step = 0.1,
                               value = 1),
                 ),
                 HTML('<details><summary>Pseudocode to generate the data</summary>'),
                 uiOutput("disc_select_DGP_formula"),
                 HTML('</details><br>')
               )
             )),
           mainPanel(
             width = 7,
             tabsetPanel(
               id = 'disc_tabs',
               type = 'tabs',
               tabPanel("Observable data",
                        br(),
                        plotOutput("disc_plot_observable", height = 600)),
               tabPanel("All data",
                        br(),
                        plotOutput("disc_plot_all", height = 600))
             )
           )
         )
)